import type { IconType } from "react-icons";
import {
  SiSelenium,
  SiCucumber,
  SiAppium,
  SiPytest,
  SiPython,
  SiOpenjdk,
  SiPostman,
  SiJenkins,
  SiGit,
  SiGithub,
  SiKubernetes,
  SiMongodb,
} from "react-icons/si";
import {
  LuTestTubeDiagonal,
  LuTestTube,
  LuNetwork,
  LuRoute,
  LuWorkflow,
  LuContainer,
  LuDatabase,
  LuBoxes,
  LuBrainCircuit,
  LuBrain,
  LuRadar,
  LuChartNetwork,
  LuWaypoints,
  LuShieldCheck,
  LuBugOff,
  LuFingerprint,
  LuScrollText,
  LuLanguages,
  LuEyeOff,
  LuCode,
} from "react-icons/lu";

export const skillIcons: Record<string, IconType> = {
  Playwright: LuTestTubeDiagonal,
  "Selenium WebDriver": SiSelenium,
  PyTest: SiPytest,
  "Cucumber (BDD)": SiCucumber,
  TestNG: LuTestTube,
  Appium: SiAppium,
  Python: SiPython,
  Java: SiOpenjdk,
  Postman: SiPostman,
  Requests: LuNetwork,
  "REST API Testing": LuRoute,
  Jenkins: SiJenkins,
  Git: SiGit,
  GitHub: SiGithub,
  "CI/CD Pipeline Integration": LuWorkflow,
  Kubernetes: SiKubernetes,
  kubectl: LuContainer,
  SQL: LuDatabase,
  MongoDB: SiMongodb,
  Milvus: LuBoxes,
  "RAG Testing": LuBrainCircuit,
  "LLM Testing": LuBrain,
  "Semantic Retrieval": LuRadar,
  MCP: LuChartNetwork,
  "Query Routing": LuWaypoints,
  "Guardrail Testing": LuShieldCheck,
  "Hallucination Testing": LuBugOff,
  RBAC: LuFingerprint,
  "Audit Logging": LuScrollText,
  "Multilingual Testing": LuLanguages,
  "Redaction Testing": LuEyeOff,
};

export function getSkillIcon(name: string): IconType {
  return skillIcons[name] ?? LuCode;
}
