export const skillDescriptions: Record<string, string> = {
  Playwright: "Primary UI & API automation framework, Cohesity & GAIA",
  "Selenium WebDriver": "Automation at Nexvant Solutions & Atos-Syntel",
  PyTest: "Python framework for API & regression suites",
  "Cucumber (BDD)": "Readable, CI-friendly BDD test scenarios",
  TestNG: "Structured test suite execution",
  Appium: "Mobile automation framework",
  Python: "Primary scripting language for API & automation",
  Java: "Used with Selenium & Cucumber automation",
  Postman: "Manual & exploratory API testing",
  Requests: "Python HTTP library for API tests",
  "REST API Testing": "End-to-end service-layer validation",
  Jenkins: "CI/CD pipeline execution",
  Git: "Version control for test code",
  GitHub: "Source hosting & collaboration",
  "CI/CD Pipeline Integration": "Wiring automated suites into release pipelines",
  Kubernetes: "Multi-node cluster deployment validation",
  kubectl: "Cluster inspection & validation, GAIA",
  AWS: "Cloud infrastructure for test environments & deployments",
  Azure: "Cloud infrastructure & DevOps workflows",
  GCP: "Cloud infrastructure for test environments & deployments",
  Linux: "Shell-based test execution & environment setup",
  "Robot Framework": "Keyword-driven automation framework",
  SQL: "Test data & backend validation",
  MongoDB: "Backend data store testing",
  Milvus: "Vector store used in GAIA's semantic retrieval",
  "RAG Testing": "Validating retrieval-augmented generation pipelines",
  "LLM Testing": "Validating model response quality",
  "Semantic Retrieval": "Testing retrieval relevance & ranking",
  MCP: "Model Context Protocol integration testing",
  "Query Routing": "Copilot/MCP routing accuracy: 46% → 100%",
  "Guardrail Testing": "Testing safety & policy guardrails",
  "Hallucination Testing": "Checking responses stay grounded in source data",
  RBAC: "Role-based access control validation",
  "Audit Logging": "Compliance-critical logging validation",
  "Multilingual Testing": "Cross-language response validation",
  "Redaction Testing": "Sensitive-data redaction validation",
};
